apiVersion: apps/v1beta1
kind: Deployment
metadata:
  name: gateway-deployment
  namespace: honda
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: gateway
    spec:
      containers:
      - name: arbgateway
        image: registry.k8s/arbgateway:IMG_ID
        resources:
          limits:
            cpu: 300m
            memory: 750Mi
        ports:
        - containerPort: 80